language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "iojs"
  - "iojs-v1.0.4"

before_install:
  - sudo chown -R $USER /usr/local 
  # Update npm itself
  - npm install -g npm
  - PATH="`npm bin -g`:`npm bin`:$PATH"
  - sh install

# Caching npm parts
cache:
  directories:
    - $HOME/.npm
    - $TRAVIS_BUILD_DIR/node_modules
